Kp/precourse intro
Ada-Accelerate-Curriculum/core-unit-1 pull request #3
Opened 2022-09-14 23:01 UTC by kyra-at-ada

Summary of Changes:
- Outline suggested path through precourse material
- Add Precourse Live topics and dates
- Summarize available resources for help

2022-09-15 18:09 UTC, kelsey-steven-ada requested changes
Overall this looks great! The zoom urls need a prefix added, otherwise just some minor suggestions.

2022-09-15 18:09 UTC, kelsey-steven-ada commented on preparing-for-ada/04-content-workflow.md
> +We expect students to have a thorough understanding of the topics under these additional units prior to your first day at Ada in addition to the primary Precourse unit content. As we progress through
This isn't necessary, but it felt a little more natural to me to group the unit content together in the first sentence.

```suggestion
We expect students to have a thorough understanding of the topics under these additional units and the primary Precourse unit prior to the first day at Ada. As we progress through Units 1-3, you'll see further topics added to these and other units. 
```

2022-09-15 18:09 UTC, kelsey-steven-ada commented on preparing-for-ada/04-content-workflow.md
> +For specific topics, we will host optional Precourse Live sessions in the [Auditorium Zoom Room](aud-accel.adadev.org) from 4:30-6:30 PST on the following dates to certain topics in more depth. We en
The zoom links were broken for me in preview mode; when I updated them locally to the full url as below it successfully opened from the Learn preview.

```suggestion
For specific topics, we will host optional Precourse Live sessions in the [Auditorium Zoom Room](http://aud-accel.adadev.org) from 4:30-6:30 PST on the following dates to certain topics in more depth. We encourage you to attend any sessions where you feel extra review of the topic would strengthen your understanding of the material. 
```

2022-09-15 18:09 UTC, kelsey-steven-ada commented on preparing-for-ada/04-content-workflow.md
> +In addition to Precourse Live, we will have instructor and TA office hours available for student questions. We also have the #study-hall channel in Slack available for questions and the Study Hall Zo
```suggestion
In addition to Precourse Live, we will have instructor and TA office hours available for student questions. We also have the #study-hall channel in Slack available for questions and the Study Hall Zoom at [accel-study-hall.adadev.org](http://accel-study-hall.adadev.org) where you can meet to work through content with peers. We encourage you to lean on your fellow Adies as well as instructors and TAs for help!
```

2022-09-15 18:09 UTC, kelsey-steven-ada commented on preparing-for-ada/04-content-workflow.md
> +| Precourse          | Intro to Dev Environment     | 10/25: Intro to Debugging & Dev Environment            |
Would it be helpful to add "tips" or "workflow" to the end of "Dev Environment" here & on line 23 to make it clearer how this is different from "Environment Setup" on the first day?

2022-09-15 18:09 UTC, kelsey-steven-ada commented on preparing-for-ada/04-content-workflow.md
> +| Software Tools     | Intro to Git                 | 11/1: Git                                              |
I think it could be helpful to expand the Precourse live description to something like "Git Basics and workflows" to give folks a little more context of what will be covered.

2022-09-15 18:09 UTC, kelsey-steven-ada commented on preparing-for-ada/04-content-workflow.md
> +| Tuesday, November 1   | Git                                               |
If we expand the Git description in the table above, we should probably use the same one here.

2022-09-20 14:36 UTC, kyra-at-ada commented on preparing-for-ada/04-content-workflow.md
> +| Software Tools     | Intro to Git                 | 11/1: Git                                              |
```suggestion
| Software Tools     | Intro to Git                 | 11/1: Git  Basics & Workflows                                |
```

2022-09-20 14:53 UTC, kelsey-steven-ada approved these changes

2022-09-20 15:19 UTC, tgoslee reviewed
The detail of the rest of this is great.

2022-09-20 15:19 UTC, tgoslee commented on preparing-for-ada/04-content-workflow.md
> +All other content is optional and intended to serve as a resource for you to review and fill in any gaps in your knowledge base. You are not required to complete all problem sets or challenge questio
Lets chat about this in our sync

2022-09-22 17:02 UTC, kyra-at-ada commented
Summary of Changes:
- Updated Content Workflow lessons to mark certain lessons as required
- Updated config.yaml to mark lessons as optional/required
    - topic title includes optional for optional lessons
    - topic descriptions mark each lesson as optional or required
    
For Review:
- Please use Learn Preview to review the lesson!

2022-09-22 17:04 UTC, tgoslee reviewed
Looks good. I like the additional column in the table with the required information

2022-09-22 20:10 UTC, merged